const PALETTE_PRESETS = [
  "BlackAndWhite",
  "Gruvbox",
  "Dracula",
  "SolarizedDark",
  "Monokai",
  "Nord",
  "Material",
  "Kanagawa",
  "Pastel",
  "Vaporwave",
  "WebSafe",
  "ObraDinn",
];

export const FILTER_DEFINITIONS = [
  { type: "INVERT", title: "Invert", options: [] },
  { type: "GRAYSCALE", title: "Grayscale", options: [] },
  {
    type: "GAUSSIAN_BLUR",
    title: "Gaussian Blur",
    options: [
      {
        label: "Sigma",
        type: "range",
        name: "sigma",
        props: { min: 0.1, max: 10, step: 0.1 },
        defaultValue: 1.0,
      },
    ],
  },
  {
    type: "SHARPEN",
    title: "Sharpen",
    options: [
      {
        label: "Amount",
        type: "range",
        name: "amount",
        props: { min: 0, max: 10, step: 0.1 },
        defaultValue: 1,
      },
      {
        label: "Radius",
        type: "range",
        name: "radius",
        props: { min: 1, max: 10, step: 0.5 },
        defaultValue: 1,
      },
    ],
  },
  {
    type: "KUWAHARA",
    title: "Kuwahara",
    options: [
      {
        label: "Style",
        type: "select",
        name: "style",
        options: ["Brushy", "Smooth"],
        defaultValue: "Brushy",
      },
      {
        label: "Radius",
        type: "range",
        name: "radius",
        props: { min: 1, max: 16, step: 1 },
        defaultValue: 10,
      },
      {
        label: "Sharpness",
        type: "range",
        name: "sharpness",
        props: { min: 0.1, max: 30, step: 0.1 },
        defaultValue: 8,
      },
      {
        label: "Anisotropy",
        type: "range",
        name: "anisotropy",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 0.65,
      },
      {
        label: "Brushiness",
        type: "range",
        name: "brushiness",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 0.65,
      },
      {
        label: "Blend",
        type: "range",
        name: "blend",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 1,
      },
    ],
  },
  {
    type: "SCALE",
    title: "Scale",
    options: [
      {
        label: "Use Uniform Scale",
        type: "select",
        name: "uniform",
        options: ["Yes", "No"],
        defaultValue: "Yes",
      },
      {
        label: "Scale",
        type: "range",
        name: "scale",
        props: { min: 0.25, max: 8, step: 0.25 },
        defaultValue: 1,
      },
      {
        label: "Scale X",
        type: "range",
        name: "scaleX",
        props: { min: 0.25, max: 8, step: 0.25 },
        defaultValue: 1,
      },
      {
        label: "Scale Y",
        type: "range",
        name: "scaleY",
        props: { min: 0.25, max: 8, step: 0.25 },
        defaultValue: 1,
      },
      {
        label: "Filter",
        type: "select",
        name: "filter",
        options: ["Nearest", "Linear"],
        defaultValue: "Nearest",
      },
    ],
  },
  { type: "SOBEL", title: "Sobel Edge", options: [] },
  {
    type: "POSTERIZE",
    title: "Posterize",
    options: [
      {
        label: "Levels",
        type: "range",
        name: "levels",
        props: { min: 2, max: 20, step: 1 },
        defaultValue: 5,
      },
    ],
  },
  {
    type: "ASCII",
    title: "ASCII Filter",
    options: [
      {
        label: "Block Size",
        type: "range",
        name: "blockSize",
        props: { min: 1, max: 32, step: 1 },
        defaultValue: 16,
      },
      {
        label: "Density",
        type: "range",
        name: "density",
        props: { min: 0.25, max: 5, step: 0.25 },
        defaultValue: 1,
      },
      {
        label: "Mode",
        type: "select",
        name: "mode",
        options: ["All", "Threshold"],
        defaultValue: "All",
      },
      {
        label: "Low Threshold",
        type: "range",
        name: "low",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 0,
      },
      {
        label: "High Threshold",
        type: "range",
        name: "high",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 1,
      },
      {
        label: "Chars",
        type: "text",
        name: "chars",
        defaultValue: ".:-=+*#%@",
      },
      { label: "Font", type: "text", name: "font", defaultValue: "Arial" },
      {
        label: "Fill Mode",
        type: "select",
        name: "fillMode",
        options: ["Color", "Transparent"],
        defaultValue: "Color",
      },
      { label: "Fill", type: "color", name: "fill", defaultValue: "#000000" },
      {
        label: "Text Color Mode",
        type: "select",
        name: "textColorMode",
        options: ["Sampled", "Custom"],
        defaultValue: "Sampled",
      },
      {
        label: "Text Color",
        type: "color",
        name: "textColor",
        defaultValue: "#ffffff",
      },
      {
        label: "Overlay",
        type: "select",
        name: "overlay",
        options: ["No", "Yes"],
        defaultValue: "No",
      },
      {
        label: "Alpha Threshold",
        type: "range",
        name: "alphaThreshold",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 0.5,
      },
    ],
  },
  {
    type: "DITHER",
    title: "Dithering",
    options: [
      {
        label: "Algorithm",
        type: "select",
        name: "algo",
        options: ["Ordered", "Stochastic", "Halftone", "Dizzy"],
        defaultValue: "Ordered",
      },
      {
        label: "Dizzy Style",
        type: "select",
        name: "dizzyStyle",
        options: ["Standard", "2x2 Bayer", "4x4 Bayer"],
        defaultValue: "Standard",
      },
      {
        label: "Levels",
        type: "range",
        name: "levels",
        props: { min: 2, max: 10, step: 1 },
        defaultValue: 2,
      },
    ],
  },
  {
    type: "PALETTE",
    title: "Palette",
    options: [
      {
        label: "Preset",
        type: "select",
        name: "preset",
        options: [...PALETTE_PRESETS, "Custom"],
        defaultValue: PALETTE_PRESETS[0],
      },
      {
        label: "Custom Colors",
        type: "customColors",
        name: "customColors",
        defaultValue: [],
      },
    ],
  },
  {
    type: "EMBOSS",
    title: "Emboss",
    options: [
      {
        label: "Strength",
        type: "range",
        name: "strength",
        props: { min: 0, max: 5, step: 0.1 },
        defaultValue: 1,
      },
    ],
  },
  {
    type: "CHROMA",
    title: "Chromatic Aberration",
    options: [
      {
        label: "Strength",
        type: "range",
        name: "strength",
        props: { min: 0, max: 50, step: 1 },
        defaultValue: 10,
      },
    ],
  },
  {
    type: "PIXELSORT",
    title: "Pixel Sort",
    options: [
      {
        label: "Mode",
        type: "select",
        name: "mode",
        options: ["Fully Sorted", "Threshold"],
        defaultValue: "Fully Sorted",
      },
      {
        label: "Low Threshold",
        type: "range",
        name: "low",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 0.2,
      },
      {
        label: "High Threshold",
        type: "range",
        name: "high",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 0.8,
      },
      {
        label: "Sort By",
        type: "select",
        name: "sortBy",
        options: [
          "Luminance",
          "Hue",
          "Saturation",
          "RGB Average",
          "Red",
          "Green",
          "Blue",
        ],
        defaultValue: "Luminance",
      },
      {
        label: "Direction",
        type: "select",
        name: "direction",
        options: [
          "Down",
          "Up",
          "Right",
          "Left",
          "Down Right",
          "Up Left",
          "Down Left",
          "Up Right",
          "Center Out ↕",
          "Center Out ↔",
          "Center Out ⤡",
          "Center Out ⤢",
          "Edges In ↕",
          "Edges In ↔",
          "Edges In ⤡",
          "Edges In ⤢",
          "Snake ↕",
          "Snake ↔",
          "Snake ⤡",
          "Snake ⤢",
          "Split ↔",
          "Split ↕",
          "Rings ↻",
          "Rings ↺",
        ],
        defaultValue: "Down",
      },
    ],
  },
  {
    type: "BLOOM",
    title: "Bloom",
    options: [
      {
        label: "Strength",
        type: "range",
        name: "strength",
        props: { min: 0, max: 3, step: 0.01 },
        defaultValue: 1,
      },
      {
        label: "Threshold",
        type: "range",
        name: "threshold",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 0.8,
      },
      {
        label: "Blur Radius",
        type: "range",
        name: "radius",
        props: { min: 1, max: 10, step: 1 },
        defaultValue: 5,
      },
    ],
  },
  {
    type: "QUADTREE",
    title: "Quadtree",
    options: [
      {
        label: "Quad Detail Threshold",
        type: "range",
        name: "threshold",
        props: { min: 0.001, max: 0.2, step: 0.001 },
        defaultValue: 0.015,
      },
      {
        label: "Max Levels",
        type: "range",
        name: "maxLevels",
        props: { min: 1, max: 9, step: 1 },
        defaultValue: 7,
      },
      {
        label: "Min Block Size",
        type: "range",
        name: "minBlockSize",
        props: { min: 1, max: 128, step: 1 },
        defaultValue: 2,
      },
      {
        label: "Mode",
        type: "select",
        name: "mode",
        options: ["All", "Threshold"],
        defaultValue: "All",
      },
      {
        label: "Low Threshold",
        type: "range",
        name: "low",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 0,
      },
      {
        label: "High Threshold",
        type: "range",
        name: "high",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 1,
      },
      {
        label: "Masked Area",
        type: "select",
        name: "maskedArea",
        options: ["Original", "Fill"],
        defaultValue: "Original",
      },
      {
        label: "Mask Fill",
        type: "select",
        name: "maskFill",
        options: ["Transparent", "Color"],
        defaultValue: "Transparent",
      },
      {
        label: "Mask Fill Color",
        type: "color",
        name: "maskFillColor",
        defaultValue: "#222222",
      },
      {
        label: "Shape",
        type: "select",
        name: "shape",
        options: ["Square", "Circle", "Triangle", "Diamond"],
        defaultValue: "Square",
      },
      {
        label: "Shape Edge Mode",
        type: "select",
        name: "shapeBounds",
        options: ["Stretch to clipped cell", "Clip to square cell"],
        defaultValue: "Stretch to clipped cell",
      },
      {
        label: "Shape Background",
        type: "color",
        name: "shapeBackgroundColor",
        defaultValue: "#222222",
      },
      {
        label: "Show Outlines",
        type: "select",
        name: "showOutlines",
        options: ["Yes", "No"],
        defaultValue: "Yes",
      },
      {
        label: "Outline Color",
        type: "color",
        name: "lineColor",
        defaultValue: "#222222",
      },
    ],
  },
  {
    type: "FILMGRAIN",
    title: "Film Grain",
    options: [
      {
        label: "Intensity",
        type: "range",
        name: "intensity",
        props: { min: 0, max: 0.2, step: 0.001 },
        defaultValue: 0.05,
      },
      {
        label: "Speed",
        type: "range",
        name: "speed",
        props: { min: 0, max: 10, step: 0.1 },
        defaultValue: 1,
      },
    ],
  },
  {
    type: "XDOG",
    title: "XDoG",
    options: [
      {
        label: "Sigma C",
        type: "range",
        name: "sigmaC",
        props: { min: 0.1, max: 10, step: 0.1 },
        defaultValue: 1.0,
      },
      {
        label: "Sigma E",
        type: "range",
        name: "sigmaE",
        props: { min: 0.1, max: 10, step: 0.1 },
        defaultValue: 1.6,
      },
      {
        label: "K",
        type: "range",
        name: "k",
        props: { min: 1.0, max: 10, step: 0.1 },
        defaultValue: 1.6,
      },
      {
        label: "Sigma M",
        type: "range",
        name: "sigmaM",
        props: { min: 0.1, max: 10, step: 0.1 },
        defaultValue: 1.0,
      },
      {
        label: "P",
        type: "range",
        name: "p",
        props: { min: 0, max: 100, step: 1 },
        defaultValue: 20,
      },
      {
        label: "Phi",
        type: "range",
        name: "phi",
        props: { min: 0.01, max: 50, step: 0.01 },
        defaultValue: 10,
      },
      {
        label: "Epsilon",
        type: "range",
        name: "epsilon",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 0.5,
      },
      {
        label: "Sigma A",
        type: "range",
        name: "sigmaA",
        props: { min: 0.1, max: 10, step: 0.1 },
        defaultValue: 1.0,
      },
    ],
  },
  {
    type: "VHS",
    title: "VHS",
    options: [
      {
        label: "Amount",
        type: "range",
        name: "amount",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 0.65,
      },
      {
        label: "Noise",
        type: "range",
        name: "noise",
        props: { min: 0, max: 2, step: 0.01 },
        defaultValue: 0.35,
      },
      {
        label: "Chroma Smear",
        type: "range",
        name: "chromaSmear",
        props: { min: 0, max: 3, step: 0.01 },
        defaultValue: 1.2,
      },
      {
        label: "Head Switch",
        type: "range",
        name: "headSwitch",
        props: { min: 0, max: 2, step: 0.01 },
        defaultValue: 1.0,
      },
    ],
  },
  {
    type: "CRT",
    title: "CRT",
    options: [
      {
        label: "Warp",
        type: "range",
        name: "warp",
        props: { min: 0, max: 2, step: 0.01 },
        defaultValue: 0.6,
      },
      {
        label: "Scanlines",
        type: "range",
        name: "scanlines",
        props: { min: 0, max: 2, step: 0.01 },
        defaultValue: 1.0,
      },
      {
        label: "Mask",
        type: "range",
        name: "mask",
        props: { min: 0, max: 2, step: 0.01 },
        defaultValue: 0.9,
      },
      {
        label: "Glow",
        type: "range",
        name: "glow",
        props: { min: 0, max: 2, step: 0.01 },
        defaultValue: 0.35,
      },
      {
        label: "Vignette",
        type: "range",
        name: "vignette",
        props: { min: 0, max: 2, step: 0.01 },
        defaultValue: 0.7,
      },
    ],
  },
  {
    type: "MINESWEEPER",
    title: "Minesweeper",
    options: [
      {
        label: "Block Size",
        type: "range",
        name: "blockSize",
        props: { min: 1, max: 64, step: 1 },
        defaultValue: 17,
      },
      {
        label: "Mode",
        type: "select",
        name: "mode",
        options: ["All", "Threshold"],
        defaultValue: "All",
      },
      {
        label: "Low Threshold",
        type: "range",
        name: "low",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 0,
      },
      {
        label: "High Threshold",
        type: "range",
        name: "high",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 1,
      },
      {
        label: "Alpha Threshold",
        type: "range",
        name: "alphaThreshold",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 0.5,
      },
      {
        label: "Overlay",
        type: "select",
        name: "overlay",
        options: ["No", "Yes"],
        defaultValue: "No",
      },
    ],
  },
  {
    type: "MINECRAFT",
    title: "Minecraft",
    options: [
      {
        label: "Block Size",
        type: "range",
        name: "blockSize",
        props: { min: 1, max: 64, step: 1 },
        defaultValue: 16,
      },
      {
        label: "Mode",
        type: "select",
        name: "mode",
        options: ["All", "Threshold"],
        defaultValue: "All",
      },
      {
        label: "Low Threshold",
        type: "range",
        name: "low",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 0,
      },
      {
        label: "High Threshold",
        type: "range",
        name: "high",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 1,
      },
      {
        label: "Alpha Threshold",
        type: "range",
        name: "alphaThreshold",
        props: { min: 0, max: 1, step: 0.01 },
        defaultValue: 0.5,
      },
      {
        label: "Overlay",
        type: "select",
        name: "overlay",
        options: ["No", "Yes"],
        defaultValue: "No",
      },
    ],
  },
];

export const FILTER_DEFINITIONS_BY_TYPE = Object.fromEntries(
  FILTER_DEFINITIONS.map((definition) => [definition.type, definition]),
);

export const ASCII_FILTER_DEFINITION = FILTER_DEFINITIONS_BY_TYPE.ASCII;
export const PIXEL_SORT_FILTER_DEFINITION =
  FILTER_DEFINITIONS_BY_TYPE.PIXELSORT;
